name: myanimelist
description: Provides wrappers for accessing the MyAnimeList API
version: 0.0.1
author: Michael Bui <maikub84@gmail.com>
homepage: https://github.com/MaikuB/myanimelist

dependencies:
  http: "^0.11.3+16"
  xml2json: "^2.0.13"

dev_dependencies:
  mockito: ^2.0.2
  test: ^0.12.35

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
