name: myanimelist
description: Provides wrappers for accessing the MyAnimeList API
version: 0.1.0
homepage: https://github.com/MaikuB/myanimelist

dependencies:
  http: ^0.12.0+2
  xml2json: ^4.1.0
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.5.2

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
